prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    ruleSelector:
      matchExpressions:
        - key: prometheus
          operator: In
          values:
            - rules

alertmanager:
  config:
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 6m
      receiver: 'null'
      routes:
      - match:
          alertname: HighCPUUsage
        receiver: 'null'
      - match:
          alertname: LowCPUUsage
        receiver: 'null'
    receivers:
      - name: 'null'
        webhook_configs:
          - send_resolved: true
            url: 'http://<AUTOSCALER_IP>:5001/webhook'

