apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
spec:
  selector:
    app: kafka-broker-1
  ports:
      - port : 9092
        targetPort: 9092  # Port exposed on the container/pod

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2
spec:
  selector:
    app: kafka-broker-2
  ports:
      - port : 9093
        targetPort: 9093

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3
spec:
  selector:
    app: kafka-broker-3
  ports:
      - port : 9094
        targetPort: 9094
